# -*- coding: utf-8 -*-
"""Comandos_pip.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuXqWDp1M6nzAhJEzbSdDqGil8bFjMkH

## Comandos PIP

Atualizar pip
"""

!pip install --upgrade pip

!python --version

"""Instalar uma biblioteca com **versão específica**


"""

!pip install tensorflow==2.10.1 -q

import tensorflow as tf
print(tf.__version__)

"""**Módulo Import**

A maneira mais simples de verificar se uma biblioteca está instalada é
tentar importá-la em seu código. Se a biblioteca estiver instalada,
a importação será bem-sucedida; caso contrário,
você receberá um erro de importação.


```
try:
    import biblioteca

    print("A biblioteca está instalada.")

    except ImportError:

        print("A biblioteca não está instalada.")
```

"""

try:
    import tensorflow as tf
    print("A biblioteca está instalada.")
except ImportError:
    print("A biblioteca não está instalada.")

"""Importar bibliotecas"""

import pandas as pd
print(pd.__version__)

import keras
import tensorflow as tf
from tensorflow import keras

"""Mostrar informações sobre a biblioteca"""

pip show tensorflow

"""Listar todas as bibliotecas instaladas"""

pip list

"""Em ambiente virtual para isolar seu projeto, deve ativar o ambiente e usar o comando **pip freeze** para **listar todas as bibliotecas instaladas dentro desse ambiente**. Ajuda a determinar se a biblioteca desejada está presente no ambiente virtual."""

pip freeze

"""Listar **apenas os pacotes que tem atualizações disponíveis**. Mostra a versão instalada e a versão disponível."""

pip list -o

"""Listar os pacotes **tensorflow**"""

pip list | grep tensorflow

"""
Desabilitar a execução antecipada, para garantir que o script esteja usando a versão correta do TensorFlow."""

tf.compat.v1.disable_eager_execution() # disabling eager execution

"""Criar um arquivo **requerimentos.txt**"""

pip freeze > requerimentos.txt

"""Para carregar os arquivos do requerimentos.txt"""

# Para instalar os pacotes listados basta usar o comando:

pip install -r requirimentos.txt

"""Fazer a instalação de uma biblioteca mais antiga e **outra versão de python**.

*Pode ser útil quando a versão atual causa quebra de código e é preciso utilizar uma versão mais antiga.*
"""

!pip install google-colab==1.0.0
# install colab's dependencies
!python -m pip install ipython==7.9.0 ipython_genutils==0.2.0 ipykernel==5.3.4 jupyter_console==6.1.0 prompt_toolkit==2.0.10 httplib2==0.17.4 astor==0.8.1 traitlets==5.7.1 google==2.0.3

!python --version

# Install python 3.11
!sudo apt-get update -y
!sudo apt-get install python3.12

# Change default python3 to 3.12
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 1

# Confirm version
!python3 --version
# Python 3.12.x

"""Referências:
- https://dataverso.com.br/como-verificar-se-uma-biblioteca-esta-instalada-no-python/

- https://stackoverflow.com/questions/68657341/how-can-i-update-google-colabs-python-version

- https://www.askpython.com/python/examples/update-python-google-colab
"""